# Classes
class Ingredient
  attr_reader name : String
  attr_reader quantity : Integer
  attr_reader unit : String

  def initialize: (name: String, quantity: Integer, unit: String) -> void
  def self.summary: (Array[Ingredient]) -> String
end
