# Classes
class Ingredient
  @name: String
  @quantity: String
  @unit: String

  def initialize: (name: String, quantity: String, unit: String) -> void
  def self.summary: (Array[String]) -> String
end
