# Classes
class Recipe
  @ingredients : Array[Ingredient]
  @instructions : Array[Instruction]
  attr_reader title : String
  def initialize: (title: String, ingredients: Array[Ingredient], instructions: Array[Instruction]) -> void
  def ingredients: -> String
  def instructions: -> String
end
